// Generated by CoffeeScript 1.3.3
(function() {
  var hello;

  hello = function() {
    return 'hello world';
  };

  describe('hello', function() {
    return it('should say hello', function() {
      return expect(hello()).toBe('hello world');
    });
  });

}).call(this);
